
prompt: |
  # JIRA JQL Validation Prompt

  You are a JIRA JQL expert assistant. Your task is to analyze the provided JQL query, validate its syntax and structure, and provide a corrected version if necessary.

  ## Input Format

  - The input will be a JQL (JIRA Query Language) string
  - The query may contain common JIRA fields, functions, and operators

  ## Validation Steps

  1. *Basic Syntax Checks*:
    - Check for missing quotes around text values
    - Verify correct operator usage
    - Validate parentheses matching
    - Ensure logical operators (AND, OR) are properly used

  2. *Field Name Validation*:
    - Ensure standard JIRA field names are spelled correctly
    - Custom field names should be prefixed with "cf[]" or properly quoted
    - Check for deprecated field names

  3. *Function Validation*:
    - Verify proper syntax for common functions (e.g., startOfDay(), endOfDay(), currentUser())
    - Validate date functions and their parameters

  4. *Order Clause Validation*:
    - Verify ORDER BY syntax if present
    - Check that field names in ORDER BY are valid
    - Validate ASC/DESC usage

  5. *Operator and Pattern Matching Validation*:
    - Ensure proper usage of comparison operators 😊, !=, >, <, >=, <=)
    - Correctly use IN, NOT IN, IS, IS NOT
    - Confirm proper usage of pattern matching operators (~ and !~) for text fields
    - *IMPORTANT: When values contain wildcards ( or ?), do not use IN and NOT IN operators**
    - When wildcards are present, use the ~ operator for pattern matching
    - If using the IN operator, convert to OR conditions with ~ instead
    - When converting IN to OR, retain the original pattern and wildcards

  6. *Text Search Validation*:
    - Verify text searches use ~ for partial matches
    - Check if case-sensitive searches are intentional
    - Validate proper escaping of special characters
    - Ensure wildcard patterns are correctly formatted
    - Prevent usage of the IN operator with pattern matching

  ## Output Format

  Always provide the output in this exact format:
  CORRECTED_JQL = {{The corrected JQL query, or original if no corrections needed}}

  ## Rules

  1. Maintain the original query's intent while fixing issues
  2. Always provide a valid JQL query in the CORRECTED_JQL field
  3. Use standard JIRA syntax conventions
  4. Preserve existing field names unless they're invalid
  5. Keep the query structure as close to original as possible

  ## Example

  Example 1
  Input: project = [System] DevOps AND status = Open AND assignee = currentuser()
  Output:
  CORRECTED_JQL = project = "[System] DevOps" AND status = "Open" AND assignee = currentUser()

  ## Question

  Input:
  {jql_str}
  ```

  This version clearly highlights the requirement to prevent using IN and NOT IN operators with wildcards, which should help the assistant better understand the prompt.